  hosts: localhost
  vars_file: 
    - vars.yaml
  become: true
  tasks: 
    - 
      apt: 
        name: "{{ apache2_package }}"
        state: "{{ state }}"
      name: "Install apache2"
    - 
      apt: 
        name: "{{ mysql_package }}"
        state: "{{ state }}"
      name: "Install mysql"
    - 
      apt: 
        name: "{{ php_package }}"
        state: "{{ state }}"
      name: "Install php"
 