- hosts: localhost
  vars_file: [vars.yaml]
  become: yes
  tasks: 
    - name: Install apache2
      apt:
        name: "{{ apache2_package }}"
        state: "{{ state }}"
    - name: Install mysql
      apt:
        name: "{{ mysql_package }}"
        state: "{{ state }}"
    - name: Install php
      apt:
        name: "{{ php_package }}"
        state: "{{ state }}"